KinoAfishaDP/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using KinoAfishaDP.Filters;
using KinoAfishaDP.Models;
using WebMatrix.WebData;

namespace KinoAfishaDP.Controllers
{

    [InitializeSimpleMembershipAttribute]
    public class HomeController : Controller
    {

        private UsersContext db = new UsersContext();
        private UsersContext userprofile = new UsersContext();

        public ActionResult Index()
        {

            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";


            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {


            ViewBag.Message = "Your contact page.";

            return View();
        }

        [Authorize] // Запрещены анонимные обращения к данной странице
        public ActionResult Cabinet()
        {
            SimpleRoleProvider roles = (SimpleRoleProvider)Roles.Provider;
            SimpleMembershipProvider membership = (SimpleMembershipProvider)Membership.Provider;


            string username = Request.IsAuthenticated ? User.Identity.Name : "nothing";
            int UserIdFromTableUsers = membership.GetUserId(username);

            var ccc = db.UserPhotoes.Where(z => z.UserName == username).ToList();
            UserPhoto che = new UserPhoto();
            foreach (var item in ccc)
            {
                che = new UserPhoto { UserPhotoId = item.UserPhotoId, UserName = item.UserName, Photo = item.Photo };
            }
            int UserId = che.UserPhotoId;
            ViewBag.zzz = UserId;



            UserPhoto userprofile = db.UserPhotoes.Find(UserId);
            if (userprofile == null)
            {
                userprofile = new UserPhoto { UserPhotoId = UserId, UserName = username, Photo = "" };
                db.UserPhotoes.Add(userprofile);
                db.SaveChanges();

            }
            else
            {
                ViewBag.Mes = "Юзер уже у нашій таблиці";
            }


            var x = Request.IsAuthenticated ? User.Identity.Name : "nothing";
            var userphoto = db.UserPhotoes.Where(z => z.UserName == x).ToList();

            ViewBag.UserPhoto = userphoto;
            return View();
        }


        [HttpPost]
        [Authorize]
        public ActionResult Cabinet(HttpPostedFileBase file)
        {
            //UsersContext user = new UsersContext();


            SimpleRoleProvider roles = (SimpleRoleProvider)Roles.Provider;
            SimpleMembershipProvider membership = (SimpleMembershipProvider)Membership.Provider;

            var x = Request.IsAuthenticated ? User.Identity.Name : "nothing";
            var userphoto = db.UserPhotoes.Where(z => z.UserName == x).ToList();
            var UserIdFromTableUsers = membership.GetUserId(x);

            var ccc = db.UserPhotoes.Where(z => z.UserName == x).ToList();
            UserPhoto che = new UserPhoto();
            foreach (var item in ccc)
            {
                che = new UserPhoto { UserPhotoId = item.UserPhotoId, UserName = item.UserName, Photo = item.Photo };
            }
            int UserId = che.UserPhotoId;

            UserPhoto photo = db.UserPhotoes.Find(UserId);

            string fileName = Guid.NewGuid().ToString();
            ViewBag.FileName = TempData.Peek("FileName") as string;
            string extension = Path.GetExtension(file.FileName);
            fileName += extension;

            List<string> extensions = new List<string>() { ".txt", ".png", ".jpg", ".pdf", ".zip", ".jpeg" };
            if (extensions.Contains(extension))
            {
                //var FileName = "/Content/Images/Uploads/" + fileName;
                file.SaveAs(Server.MapPath("/Content/Images/Uploads/" + fileName));
                var FileName = "/Content/Images/Uploads/" + fileName;
                photo.Photo = FileName;

                db.Entry(photo).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.Message = "Файл сохранен";
            }
            else
            {
                var FileName = "";
                photo.Photo = FileName;

                db.Entry(photo).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.Message = "Ошибка. Допустимые расширения файлов - '.txt', '.png', '.jpg', '.pdf', '.zip'";
            }



            return RedirectToAction("Cabinet");
        }






        [Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        public ActionResult AdminPanel()
        {
            ViewBag.Message = "Admin Panel.";

            return View();
        }

        [Authorize(Roles = "Admin, Moderator")] // К данному методу действия могут получать доступ только пользователи с ролью Admin и Moderator
        public ActionResult ModeratorPanel()
        {
            ViewBag.Message = "Moderator Panel.";

            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult AdminPanel(string list1)
        {
            switch (list1)
            {
                  case "Films": return RedirectToAction("Index", "Films"); 
                  case "Sessions":  return RedirectToAction("Index", "Sessions"); 
                  case "MovieHouses": return RedirectToAction("Index", "MovieHouses"); 
                  case "UserComments": return RedirectToAction("Index", "UserComments"); 
                  default: return View();
            }
            
            
        }

        public ActionResult CreateUser()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult CreateUser(string NameOfUser, string ListOfUser, string PasOfUser)
        {
            SimpleRoleProvider roles = (SimpleRoleProvider)Roles.Provider;
            SimpleMembershipProvider membership = (SimpleMembershipProvider)Membership.Provider;



            if (membership.GetUser(NameOfUser, false) != null)
            {
                return Content("Такий користувач уже існує");
            }

            else
            {
                UserPhoto userprofile = new UserPhoto { UserPhotoId = 1, UserName = NameOfUser, Photo = "" };
                db.UserPhotoes.Add(userprofile);
                db.SaveChanges();
                membership.CreateUserAndAccount(NameOfUser, PasOfUser); // создание пользователя
                roles.AddUsersToRoles(new[] { NameOfUser }, new[] { ListOfUser }); // установка роли для пользователя
            }

            return RedirectToAction("Index", "Home");
        }

        public ActionResult DeleteUser(int id = 0)
        {
            var user = userprofile.UserProfiles.ToList();
            SimpleRoleProvider roles = (SimpleRoleProvider)Roles.Provider;
            SimpleMembershipProvider membership = (SimpleMembershipProvider)Membership.Provider;
            
            UserProfile profile = userprofile.UserProfiles.Find(id);
            
            if (profile == null)
            {
                return View(user);
            }
            else
            {

                UserPhoto userphoto = db.UserPhotoes.FirstOrDefault(x => x.UserName == profile.UserName);

               var roole = roles.GetRolesForUser(profile.UserName);
               roles.RemoveUsersFromRoles(new[]{profile.UserName}, roole);
                membership.DeleteUser(profile.UserName, true);


              
                db.UserPhotoes.Remove(userphoto);
                db.SaveChanges();

                var autorised = Request.IsAuthenticated ? User.Identity.Name : "nothing";
                if (autorised == profile.UserName)
                {
                    WebSecurity.Logout();
                }

               

                TempData["_UserRole"] = "Prosto";
                return RedirectToAction("DeleteUser");
            }


        }
    }
}

KinoAfishaDP/Controllers/UserPhotoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KinoAfishaDP.Models;

namespace KinoAfishaDP.Controllers
{
    public class UserPhotoesController : Controller
    {
        private AFISHAContext db = new AFISHAContext();

        //
        // GET: /UserPhotoes/
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Index( string nickname,int? id)
        {
            var prof = nickname !=null ? db.UserPhotoes.Where(x => x.UserName.Contains(nickname) ) : db.UserPhotoes;
            var profile = prof.Join(db.UserComments,
                x=>x.UserName,
                c=>c.UserNickName,
                (x,c)=> new Profile{
                NAME=x.UserName,
                PHOTO=x.Photo,
                EMAIL=c.E_mail,
                ProfileID=x.UserPhotoId});

            return View(profile.Distinct().ToList());
        }
        [HttpPost]
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Index(string name)
        {
            var photoes =name!=""? db.UserPhotoes.Where(x=>x.UserName.ToUpper().Contains(name.ToUpper())):db.UserPhotoes;
            var profile = photoes.Join(db.UserComments,
               x => x.UserName,
               c => c.UserNickName,
               (x, c) => new Profile
               {
                   NAME = x.UserName,
                   PHOTO = x.Photo,
                   EMAIL = c.E_mail,
                   ProfileID = x.UserPhotoId
               });

            return View(profile.Distinct().ToList());
           
        }
        //
        // GET: /UserPhotoes/Details/5
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Details(int id = 0)
        {
            UserPhoto userphoto = db.UserPhotoes.Find(id);
            if (userphoto == null)
            {
                return HttpNotFound();
            }
            return View(userphoto);
        }

        //
        // GET: /UserPhotoes/Create
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /UserPhotoes/Create

        [HttpPost]
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Create(UserPhoto userphoto)
        {
            if (ModelState.IsValid)
            {
                db.UserPhotoes.Add(userphoto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userphoto);
        }

        //
        // GET: /UserPhotoes/Edit/5
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Edit(int id = 0)
        {
            UserPhoto userphoto = db.UserPhotoes.Find(id);
            if (userphoto == null)
            {
                return HttpNotFound();
            }
            return View(userphoto);
        }

        //
        // POST: /UserPhotoes/Edit/5

        [HttpPost]
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Edit(UserPhoto userphoto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userphoto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userphoto);
        }

        //
        // GET: /UserPhotoes/Delete/5
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Delete(int id = 0)
        {
            UserPhoto userphoto = db.UserPhotoes.Find(id);
            if (userphoto == null)
            {
                return HttpNotFound();
            }
            return View(userphoto);
        }

        //
        // POST: /UserPhotoes/Delete/5

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult DeleteConfirmed(int id)
        {
            UserPhoto userphoto = db.UserPhotoes.Find(id);
            db.UserPhotoes.Remove(userphoto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

KinoAfishaDP/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

KinoAfishaDP/Views/Home/AdminPanel.cshtml
@{
    ViewBag.Title = "Admin Panel";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
    
</hgroup>

@using (Html.BeginForm("AdminPanel", "Home"))
        {
             
             
    @Html.DropDownList("list1",
                        new SelectList(new[] { "Films","Sessions", "MovieHouses","UserComments"}))              
           
            <input class="btn btn-default" type="submit" name="operation" value="Перейти до редагування"/> 
        }
@if(ViewBag.Result!=null)
              {
                  <h3>Результат = @ViewBag.Result</h3>
              }




<br />
<div class="btn btn-default">@Html.ActionLink("Створити нового користувача","CreateUser","Home") </div>
<div class="btn btn-default">
    @Html.ActionLink("Редагування коментарів", "Index", "UserComments") </div >
    <div class="btn btn-default">@Html.ActionLink("Видалити користувача", "DeleteUser", "Home") </div>

<h3>ОБОВ'ЯЗКИ АДМІНІСТРАТОРА</h3>
<h4>Підтримувати порядок та чистоту на порталі:</h4>
<ul>
    <li>Ведення БД: "Фільми", "Кінотеатри", "Сеанси".</li>   
    <li>Слідкувати за актуальністю та коректністю інформації, що надається відвідувачам.</li>
    <li>Відбирати якісний контент та вчасно інформувати користувачів про нові заходи.</li>
    <li>При неодноразовому порушенні правил видаляти профіль користувача-порушника назавжди.</li>
    <li>Повідомляти розробників веб-додатку про баги у функціоналі.</li>   
</ul>
<h4>Вам надається доступ до всіх функціональних  можливостей модератора</h4>

KinoAfishaDP/Views/Home/Cabinet.cshtml
@model KinoAfishaDP.Models.UserPhoto
@{
    ViewBag.Title = "Ваш особистий профіль";
    List<KinoAfishaDP.Models.UserPhoto> userphoto = ViewBag.UserPhoto;
    
}
@*@model KinoAfishaDP.Models.LoginModel*@

<div class="row">
    <div class="col-lg-5">
        <hgroup class="title">
            <h3>@ViewBag.Title.</h3>

        </hgroup>
        <div>



            @if (Request.IsAuthenticated)
            {
                <text>
                    Привіт, @User.Identity.Name

                </text>
            }


        </div>

        @foreach (var item in userphoto)
        {

            <img width="250" height="200" src="@item.Photo" />
            <br />



        }

        <h3>Виберіть файл для загрузки</h3>

        <form action="@Url.Action("Cabinet", "Home")" method="post" enctype="multipart/form-data">
            Файл -
            <input type="file" name="file"  />
            <br />
            <input type="submit" value="Відправити фотографію" />

        </form>
    </div>
    <div class="col-lg-7">
        <h3>Правила поведінки:</h3>
        
        <ul>
            <li>Використовувати нецензурні вирази в будь-якій формі.</li>
            <li>Ображати і дискримінувати учасників за будь-якою ознакою.</li>
            <li>Ображати культуру, традиції та інші національні цінності будь-якого народу чи країни.</li>
            <li>Зловживати режимом <b>Caps Lock</b> і великим розміром шрифту як в назві повідомлення, так і в ньому самому.</li>
            <li>Розсилати спам за допомогою особистих повідомлень і e - mail.</li>
            <li>Забороняється до публікації свідомо помилкова інформація, наклеп.</li>
            
        </ul>
        <h3>Санкції за порушення правил:</h3>

        <ul>
            <li>усне попередженн;</li>
            <li>винесення попередження у вигляді жовтої або червоної картки;</li>
            <li>позбавлення прав на публікацію повідомлень;</li>
            <li>позбавлення всіх прав - використовується як крайня міра покарання за тяжкі порушення;</li>
            <li>бан за ip адресою і / або видалення користувача - використовується як міра покарання за особливо тяжкі порушення.</li>
            

        </ul>
    </div>
</div>
 

KinoAfishaDP/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        @*<span class="label">Main:</span>*@
        <span>+38 (095)339-3612</span><br />
        <span>
            <a href="https://vk.com/id151572711"title="В соціальній мережі">vk.com/id151572711</a>   
        </span>
    </p>
   @* <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>*@
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    @*<p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>*@
    <p>
        @*<span class="label">General:</span>*@
        <span><a href="mailto:yurapuk452@gmail.com">yurapuk452@gmail.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        Україна<br />
        Дніпропетровськ, Вернадського 6
    </p>
</section>

KinoAfishaDP/Views/Home/CreateUser.cshtml
@{
    ViewBag.Title = "CreateUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CreateUser</h2>

@using (Html.BeginForm("CreateUser", "Home"))
{
    <label>Name</label>@Html.TextBox("NameOfUser") <br />
    @Html.ValidationMessage("NameOfUser")<br />
    <label>Password</label>@Html.TextBox("PasOfUser") <br />
    <label>Role</label>@Html.DropDownList("ListOfUser",
                                          new SelectList(new[] {"Admin","Moderator"}))<br />
    <input type ="submit",value="Register User"/>
}

KinoAfishaDP/Views/Home/DeleteUser.cshtml
@model IEnumerable<KinoAfishaDP.Models.UserProfile>

@{
    ViewBag.Title = "DeleteUser";
}

<h2>DeleteUser</h2>

<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
          
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                    @Html.ActionLink("DeleteUser", "DeleteUser", new { id = item.UserId })<br />
               
            </td>
        </tr>
    }

</table>

KinoAfishaDP/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Кіноафіша";
}
@*@section featured {*@
    <section class="featured">
        <div class="content-wrapper">
           
         
         
            @Html.Action("Index","Films")
            
        </div>
    </section>
@*}*@

KinoAfishaDP/Views/Home/ModeratorPanel.cshtml
@{
    ViewBag.Title = "Moderator Panel";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
   @* <h2>@ViewBag.Message</h2>*@

</hgroup>
<br />
    <div class="btn btn-default">@Html.ActionLink("Коментарі користувачів","Index","UserComments")</div>
    <div class="btn btn-default">@Html.ActionLink("Особистий профіль користувачів","Index","UserPhotoes")</div>

<h3>ОБОВ'ЯЗКИ МОДЕРАТОРА</h3>
    <h4>Підтримувати порядок та чистоту на порталі:</h4>
<ul>
    <li>якщо учасник форуму використовує в своїх повідомленнях нецензурну лексику або флуд, то модератор повинен попередити його про порушення через систему "Особистих повідомлень" і видалити повідомлення з теми.</li>
    <li>якщо учасник проігнорував повідомлення модератора і продовжує інтенсивно писати аналогічні повідомлення, модератор повинен повідомити про це адміністратора, який в свою чергу знищить нік користувача-порушника назавжди.</li>
    <li>редагувати та видаляти повідомленняінших користувачів. </li>
</ul>