KinoAfishaDP/Controllers/MovieHousesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KinoAfishaDP.Models;

namespace KinoAfishaDP.Controllers
{
    public class MovieHousesController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /MovieHouses/

        public ActionResult Index(string name)
        {
            TempData["cinemainfo"] = name;

            var stations = name != null ? db.MovieHouses.Where(x => x.MovieHouseName.Contains(name)).OrderByDescending(x => x.MovieHouseRating) : db.MovieHouses.OrderByDescending(x => x.MovieHouseRating);
            //var stations = db.MovieHouses.Take(5).OrderByDescending(x => x.MovieHouseRating);
            //var stations = name != null ? db.MovieHouses.Where(x => x.MovieHouseName.Contains(name)) : db.MovieHouses;

            return View(stations.ToList());
        }
        [HttpPost]
        public ActionResult Index(string action, string name1)
        {

            var NAME = TempData.Peek("cinemainfo") as string;
            MovieHouse reiting = db.MovieHouses.Find(1);
            switch (action)
            {
                case "add": { reiting.MovieHouseRating++; } break;
                case "minus": { reiting.MovieHouseRating--; } break;

                default: ViewBag.Result = "ERRor"; break;
            }
            
            db.Entry(reiting).State = EntityState.Modified;
            db.SaveChanges();

            MovieHouse reiting1 = db.MovieHouses.Find(1);
            
            var stations = NAME != null ? db.MovieHouses.Where(x => x.MovieHouseName.Contains(NAME)).OrderByDescending(x => x.MovieHouseRating) : db.MovieHouses.OrderByDescending(x => x.MovieHouseRating);


            return View(stations.ToList());
        }

        
        //
        // GET: /MovieHouses/Details/5
        [Authorize(Roles = "Admin")] 
        public ActionResult Details(int id = 0)
        {
            MovieHouse moviehouse = db.MovieHouses.Find(id);
            if (moviehouse == null)
            {
                return HttpNotFound();
            }
            return View(moviehouse);
        }

        //
        // GET: /MovieHouses/Create
        [Authorize(Roles = "Admin")] 
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /MovieHouses/Create

        [HttpPost]
        [Authorize(Roles = "Admin")] 
        public ActionResult Create(MovieHouse moviehouse)
        {
            if (ModelState.IsValid)
            {
                db.MovieHouses.Add(moviehouse);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(moviehouse);
        }

        //
        // GET: /MovieHouses/Edit/5
        [Authorize(Roles = "Admin")] 
        public ActionResult Edit(int id = 0)
        {
            MovieHouse moviehouse = db.MovieHouses.Find(id);
            if (moviehouse == null)
            {
                return HttpNotFound();
            }
            return View(moviehouse);
        }

        //
        // POST: /MovieHouses/Edit/5

        [HttpPost]
        [Authorize(Roles = "Admin")] 
        public ActionResult Edit(MovieHouse moviehouse)
        {
            if (ModelState.IsValid)
            {
                db.Entry(moviehouse).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(moviehouse);
        }

        //
        // GET: /MovieHouses/Delete/5
        [Authorize(Roles = "Admin")] 
        public ActionResult Delete(int id = 0)
        {
            MovieHouse moviehouse = db.MovieHouses.Find(id);
            if (moviehouse == null)
            {
                return HttpNotFound();
            }
            return View(moviehouse);
        }

        //
        // POST: /MovieHouses/Delete/5

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")] 
        public ActionResult DeleteConfirmed(int id)
        {
            MovieHouse moviehouse = db.MovieHouses.Find(id);
            db.MovieHouses.Remove(moviehouse);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }


        public JsonResult GetData()
        {
            string cinemainfo=TempData.Peek("cinemainfo") as string;
           
            
            var stations = cinemainfo != null ? db.MovieHouses.Where(x => x.MovieHouseName.Contains(cinemainfo)).ToList() : db.MovieHouses.ToList();
            

            return Json(stations, JsonRequestBehavior.AllowGet);
        }
    }
}

KinoAfishaDP/Controllers/SessionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KinoAfishaDP.Models;

namespace KinoAfishaDP.Controllers
{
    public class SessionsController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Sessions/

        public ActionResult Index(string NameOfFilm)
        {
            TempData["NameOfFilm"] = NameOfFilm;
            ViewBag.FilmName = new SelectList(db.Films, "FilmName", "FilmName");
            ViewBag.Cinema = new SelectList(db.MovieHouses, "MovieHouseName", "MovieHouseName");

            if (TempData.Peek("_UserRole") as string == "Admin" || TempData.Peek("_UserRole") as string == "Moderator")
            {
                var sessions = db.Sessions.Include(s => s.Film).Include(s => s.MovieHouse);
                var sessions1 = NameOfFilm != null ? sessions.Where(x => x.Film.FilmName.ToUpper()
                                                             .Contains(NameOfFilm.ToUpper()))
                                                             .Where(x=>x.SessionTimePokaz>=DateTime.Now)             
                                                             .OrderByDescending(x => x.SessionTimePokaz) : sessions.OrderByDescending(x => x.SessionTimePokaz);
                return View(sessions1.ToList());
            }
            else 
            {
                var sessions = db.Sessions.Include(s => s.Film).Include(s => s.MovieHouse);
                var sessions1 = NameOfFilm != null ? sessions.Where(x => x.Film.FilmName.ToUpper().Contains(NameOfFilm.ToUpper())).Where(x => x.SessionTimePokaz > DateTime.Now) : sessions.Where(x => x.SessionTimePokaz > DateTime.Now);
                return View(sessions1.ToList());
            }
           
        }
        [HttpPost]
        public ActionResult Index(string FilmName, string Cinema, DateTime? start,DateTime? end)
        {
           
            var sessions = db.Sessions.Include(s => s.Film).Include(s => s.MovieHouse);

            ViewBag.FilmName = new SelectList(db.Films, "FilmName", "FilmName");
            ViewBag.Cinema = new SelectList(db.MovieHouses, "MovieHouseName", "MovieHouseName");

            var NAME = FilmName != "" ? sessions.Where(x => x.Film.FilmName==FilmName) : sessions;
            var CINEMA = Cinema != "" ? sessions.Where(x => x.MovieHouse.MovieHouseName==Cinema) : sessions;


            var TIME1 = start != null ? sessions.Where(x => x.SessionTimePokaz >= start) : sessions;
            var TIME2 = end!=null? sessions.Where(x=>x.SessionTimePokaz<=end):sessions;

            if (TempData.Peek("_UserRole") as string == "Admin" || TempData.Peek("_UserRole") as string == "Moderator")
            {
                var All = NAME.Intersect(CINEMA).Intersect(TIME1).Intersect(TIME2);
               
                return View(All.ToList());
            }
            else
            {
                var All = NAME.Intersect(CINEMA).Intersect(TIME1).Intersect(TIME2);
                return View(All.Where(x => x.SessionTimePokaz >= DateTime.Now));

            }
          


           
            
        }

        ////Для адміна......................................
        //................................................
        //................................................
        //...............................................
       
        // GET: /Sessions/Details/5
        [Authorize(Roles = "Admin")] 
        public ActionResult Details(int id = 0)
        {
            Session session = db.Sessions.Find(id);
            if (session == null)
            {
                return HttpNotFound();
            }
            return View(session);
        }

        //
        // GET: /Sessions/Create
        [Authorize(Roles = "Admin")] 
        public ActionResult Create()
        {
            
            ViewBag.FilmId = new SelectList(db.Films, "FilmId", "FilmName");
            ViewBag.MovieHouseId = new SelectList(db.MovieHouses, "MovieHouseId", "MovieHouseName");
            return View();
        }

        //
        // POST: /Sessions/Create

        [HttpPost]
        [Authorize(Roles = "Admin")] 
        public ActionResult Create(Session session)
        {
            

            if(ModelState.IsValid)
            {
                db.Sessions.Add(session);
                db.SaveChanges();
               
                return RedirectToAction("Index");
            }

            ViewBag.FilmId = new SelectList(db.Films, "FilmId", "FilmName", session.FilmId);
            ViewBag.MovieHouseId = new SelectList(db.MovieHouses, "MovieHouseId", "MovieHouseName", session.MovieHouseId);
            
            return View(session);
        }

        //
        // GET: /Sessions/Edit/5
        [Authorize(Roles = "Admin")] 
        public ActionResult Edit(int id = 0)
        {
            Session session = db.Sessions.Find(id);
            if (session == null)
            {
                return HttpNotFound();
            }
            ViewBag.FilmId = new SelectList(db.Films, "FilmId", "FilmName", session.FilmId);
            ViewBag.MovieHouseId = new SelectList(db.MovieHouses, "MovieHouseId", "MovieHouseName", session.MovieHouseId);
            return View(session);
        }

        //
        // POST: /Sessions/Edit/5

        [HttpPost]
        [Authorize(Roles = "Admin")] 
        public ActionResult Edit(Session session)
        {
            if (ModelState.IsValid)
            {
                db.Entry(session).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FilmId = new SelectList(db.Films, "FilmId", "FilmName", session.FilmId);
            ViewBag.MovieHouseId = new SelectList(db.MovieHouses, "MovieHouseId", "MovieHouseName", session.MovieHouseId);
            return View(session);
        }

        //
        // GET: /Sessions/Delete/5
        [Authorize(Roles = "Admin")] 
        public ActionResult Delete(int id = 0)
        {
            Session session = db.Sessions.Find(id);
            if (session == null)
            {
                return HttpNotFound();
            }
            return View(session);
        }

        //
        // POST: /Sessions/Delete/5

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")] 
        public ActionResult DeleteConfirmed(int id)
        {
            Session session = db.Sessions.Find(id);
            db.Sessions.Remove(session);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

KinoAfishaDP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ua">
<head>
    <meta charset="utf-8" />

    @Scripts.Render("~/bundles/jquery")



    <title>@ViewBag.Title - My ASP.NET MVC Application</title>

    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
     
    @Styles.Render("~/Content/css")
   <link rel="stylesheet" href="~/Content/bootstrap.min.css"/>
    @Scripts.Render("~/bundles/modernizr")
   
    @if (IsSectionDefined("Owl"))
    {
 @RenderSection("Owl") 
    }

    @if (IsSectionDefined("Commentstyle"))
    {
 @RenderSection("Commentstyle") 
    }


    <script type="text/javascript" src="~/Content/js/script.js"></script>
    

    @*Відповідає за таймпікер*@
    <link rel="stylesheet" type="text/css" href="~/Content/js/jquery.datetimepicker.css" />
    <style type="text/css">
        .custom-date-style
        {
            background-color: red !important;
        }

        .input
        {
        }

        .input-wide
        {
            width: 500px;
        }
    </style>
    @*Відповідає за таймпікер*@

</head>

<body>
    <header>

        <div class="content-wrapper">
            @* Створю якорь*@
            <span id="top"></span>
           
            <div class="float-left">
                <a title="Кіно афіша ДП" href="/Home/Index">
                    <img src="~/Images/logo.jpg" width="150px">
                </a>
            </div>


            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Головна", "Index", "Home")</li>
                        <li>@Html.ActionLink("Сеанси", "Index", "Sessions")</li>
                        <li>@Html.ActionLink("Кінотеатри", "Index", "MovieHouses")</li>
                        <li>@Html.ActionLink("Кабінет", "Cabinet", "Home")</li>
                       
                            <li>@Html.ActionLink("Адміністратору", "AdminPanel", "Home")</li>
                       
                       
                            <li>@Html.ActionLink("Модератору", "ModeratorPanel", "Home")</li>
                       
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
            </div>
        </div>
    </footer>
    @if (IsSectionDefined("Golos"))
    {
        @RenderSection("Golos") 
    }

    @RenderSection("scripts", required: false)

    <p style="margin-left: 0px;" id="back-top"><a href="#top"><span></span>Наверх</a></p>


</body>

@if (IsSectionDefined("Picker"))
{
    @RenderSection("Picker") 
}
@if (IsSectionDefined("OwlScript"))
{
    @RenderSection("OwlScript") 
}


</html>

KinoAfishaDP/Views/Shared/_Layout1.cshtml
!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />

    @Scripts.Render("~/bundles/jquery")

    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
  
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @if (IsSectionDefined("Owl"))
    {
        @RenderSection("Owl") 
    }
       
</head>
<body>
    <header >

          
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
            </div>
        </div>
    </footer>

    @RenderSection("scripts", required: false)
    
    <p style="margin-left: 0px;" id="back-top"><a href="#top"><span></span>Наверх</a></p>
 
  @RenderSection("Golos")
</body>


@if (IsSectionDefined("OwlScript"))
{
    @RenderSection("OwlScript") 
}

</html>